#pragma config(Sensor, port9,  ultra,          sensorVexIQ_Distance)
#pragma config(Sensor, port11, rightColor,     sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port12, leftColor,      sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor5,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float leftStick;
float rightStick;

float leftFinal;
float rightFinal;

int counter = 0;

float distanceRaw;
float distance;

task main(){
	while(true){

		distanceRaw = getDistanceValue(ultra);
		distance = distanceRaw / 25.4;

		if(vexRT[BtnEUp]){
			leftFinal = 30;
			rightFinal = 30;
			while(vexRT[BtnEDown] == 0){
				if(getColorValue(leftColor) < 350){
					leftFinal -= 2;
					wait1Msec(7);
				}
				else{
					leftFinal = 30;
				}

				if(getColorValue(rightColor) < 350){
					rightFinal -= 2;
					wait1Msec(7);
				}
				else{
					rightFinal = 30;
				}
				setMotorSpeed(rightMotor,rightFinal);
				setMotorSpeed(leftMotor,leftFinal);
			}
		}
		if(vexRT[BtnFUp]){
			counter = 1;
		}
		else if(vexRT[BtnFDown]){
			counter = 0;
		}

		if(counter == 0) {
			leftStick = vexRT[ChA] * vexRT[ChA];
			rightStick = vexRT[ChD] * vexRT[ChD];

			leftFinal = leftStick / 100;
			rightFinal = rightStick / 100;

			if(vexRT[ChA] < 0){
				leftFinal = leftFinal * -1;
			}
			if(vexRT[ChD] < 0){
				rightFinal = rightFinal * -1;
			}
		}
		else if(counter == 1) {
			leftFinal = vexRT[ChA];
			rightFinal =vexRT[ChD];
		}


		displayCenteredTextLine(0, "Hue: %f", getColorValue(leftColor));
		displayCenteredTextLine(1, "counter %d", counter);
		displayCenteredTextLine(2, "Right %f", rightFinal);
		displayCenteredTextLine(3, "Left %f", leftFinal);
		//displayCenteredTextLine(2, "Distance: %f inches", distance);

		if(distance < 8){
			setMotorSpeed(leftMotor, -100);
			setMotorSpeed(rightMotor, -100);
			wait1Msec(1000);
		}

		setMotorSpeed(leftMotor,leftFinal);
		setMotorSpeed(rightMotor,rightFinal);
	}
}
