#pragma config(Sensor, port1,  touchLeft,      sensorVexIQ_LED)
#pragma config(Sensor, port3,  gyro,           sensorVexIQ_Gyro)
#pragma config(Sensor, port7,  touchRight,     sensorVexIQ_LED)
#pragma config(Sensor, port9,  ultra,          sensorVexIQ_Distance)
#pragma config(Sensor, port11, rightColor,     sensorVexIQ_ColorGrayscale)
#pragma config(Sensor, port12, leftColor,      sensorVexIQ_ColorGrayscale)
#pragma config(Motor,  motor5,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float leftStick;
float rightStick;

float leftFinal;
float rightFinal;

int counter = 0;

float distanceRaw;
float distance;

int degrees;

task main(){
	while(true){

		distanceRaw = getDistanceValue(ultra);
		distance = distanceRaw / 25.4;

		degrees = getGyroDegrees(gyro);

		if(vexRT[BtnEUp]){
			leftFinal = 30;
			rightFinal = 30;
			while(vexRT[BtnEDown] == 0){
				if(getColorValue(leftColor) < 350){
					leftFinal -= 1;
					wait1Msec(5);
				}
				else{
					leftFinal =30;
				}

				if(getColorValue(rightColor) < 350){
					rightFinal -= 1;
					wait1Msec(5);
				}
				else{
					rightFinal = 30;
				}
				setMotorSpeed(leftMotor, leftFinal);
				setMotorSpeed(rightMotor, rightFinal);
			}
		}

		if(vexRT[BtnFUp]){
			counter = 1;
		}
		else if(vexRT[BtnFDown]){
			counter = 0;
		}
		if(counter == 0){
			leftStick = vexRT[ChA] * vexRT[ChA];
			rightStick = vexRT[ChD] * vexRT[ChD];

			leftFinal = leftStick / 100;
			rightFinal = rightStick / 100;

			if(vexRT[ChA] < 0){
				leftFinal = leftFinal * -1;
			}
			if(vexRT[ChD] < 0){
				rightFinal = rightFinal * -1;
			}
		}

		else if(counter == 1){
			leftFinal = vexRT[ChA];
			rightFinal = vexRT[ChD];
		}



		displayCenteredTextLine(0, "Hue: %f", getColorValue(leftColor));
		displayCenteredTextLine(1, "Counter %d", counter);
		//displayCenteredTextLine(2, "right %f", rightFinal);
		//displayCenteredTextLine(3, "left %f", leftFinal);
		displayCenteredTextLine(2, "Distance: %f inches", distance);
		displayCenteredTextLine(3, "Rotation: %d degrees", degrees);

		if(vexRT[BtnRUp]){
			resetGyro(gyro);
		}

		if(distance < 8){
			setMotorSpeed(leftMotor, -100);
			setMotorSpeed(rightMotor, -100);
			wait1Msec(1000);
		}

		if(leftFinal > 0){
			setTouchLEDColor(touchLeft, colorGreen);
			setTouchLEDBrightness(touchLeft, leftFinal);
		}
		else if(leftFinal < 0){
			setTouchLEDColor(touchLeft, colorRed);
			setTouchLEDBrightness(touchLeft, (-1 * leftFinal));

		}
		else{
			setTouchLEDColor(touchLeft,colorBlue);
			setTouchLEDBrightness(touchLeft, 100);
		}

		if(rightFinal > 0){
			setTouchLEDColor(touchRight, colorGreen);
			setTouchLEDBrightness(touchRight, rightFinal);
		}
		else if(rightFinal < 0){
			setTouchLEDColor(touchRight, colorRed);
			setTouchLEDBrightness(touchRight, (-1 * rightFinal));
		}
		else{
			setTouchLEDColor(touchRight, colorBlue);
			setTouchLEDBrightness(touchRight, 100);
		}
		setMotorSpeed(leftMotor, leftFinal);
		setMotorSpeed(rightMotor, rightFinal);
	}
}
