#pragma config(Motor,  motor5,          leftMotor,     tmotorVexIQ, PIDControl, driveLeft, encoder)
//,#pragma config(Motor,  motor6,          rightMotor,    tmotorVexIQ, PIDControl, reversed, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main(){
	while(true){
		setMotorSpeed(leftMotor, vexRT[ChA]);
	}
}
